#!/bin/sh

### BEGIN INIT INFO
# Provides:          ${application.name}
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Initscript for ${application.name} 
### END INIT INFO

NAME=${application.name}
PIDFILE=/var/run/$NAME.pid
DAEMON=/usr/bin/java
DAEMON_OPTS="-jar /var/lib/${application.name}/happy-chameleon-jar.jar --spring.config.location=/etc/${application.name}/application.properties"

# Define LSB log_* functions.
# Depend on lsb-base (>= 3.2-14) to ensure that this file is present
# and status_of_proc is working.
. /lib/lsb/init-functions

start(){
    start-stop-daemon --start --quiet --pidfile $PIDFILE --background --make-pidfile --exec $DAEMON -- $DAEMON_OPTS
}

stop(){
    start-stop-daemon --stop --quiet --oknodo --pidfile $PIDFILE --remove-pidfile --retry TERM/30/KILL/10
}

status(){
	start-stop-daemon --status --quiet --pidfile $PIDFILE
}

case "$1" in
  start)
	start
	;;
  stop)
	stop
	;;
  restart)
	stop
	start
	;;
  status)
	status
	exit $?
	;;
  *)
	log_daemon_msg "Usage: "$1" {start|stop|restart|status}"
	exit 3
esac
